/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-07-16 04:48:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mobile.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import java.security.Key;
import javax.crypto.spec.SecretKeySpec;
import io.jsonwebtoken.*;
import org.apache.commons.text.StringEscapeUtils;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("io.jsonwebtoken");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.security.Key");
    _jspx_imports_classes.add("javax.crypto.spec.SecretKeySpec");
    _jspx_imports_classes.add("org.apache.commons.text.StringEscapeUtils");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

request.setCharacterEncoding("UTF-8");

boolean isLoggedIn = false;
String username = "", email = "", introOutput = "";

String dbURL = System.getenv("DB_URL");
String dbUser = System.getenv("DB_USER");
String dbPassword = System.getenv("DB_PASSWORD");

// JWT 쿠키 추출
Cookie[] cookies = request.getCookies();
String token = null;
if (cookies != null) {
    for (Cookie cookie : cookies) {
        if ("authToken".equals(cookie.getName())) {
            token = cookie.getValue();
            break;
        }
    }
}

// JWT 검증
if (token != null) {
    try {
        String jwtSecret = System.getenv("JWT_SECRET");
        if (jwtSecret != null) {
            byte[] keyBytes = jwtSecret.getBytes("UTF-8");
            Key signingKey = new SecretKeySpec(keyBytes, SignatureAlgorithm.HS256.getJcaName());

            Claims claims = Jwts.parserBuilder()
                .setSigningKey(signingKey)
                .build()
                .parseClaimsJws(token)
                .getBody();

            username = claims.getSubject();
            isLoggedIn = true;
        } else {
            out.println("환경변수 JWT_SECRET이 설정되지 않았습니다.");
        }
    } catch (Exception e) {
        getServletContext().log("JWT 검증 실패", e);
    }
}

if (!isLoggedIn) {
    response.sendRedirect("/mobile/login/login.jsp");
    return;
}

// 사용자 이메일 조회
try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    try (Connection conn = DriverManager.getConnection(dbURL, dbUser, dbPassword);
         PreparedStatement pstmt = conn.prepareStatement("SELECT email FROM users WHERE username = ?")) {
        pstmt.setString(1, username);
        try (ResultSet rs = pstmt.executeQuery()) {
            if (rs.next()) {
                email = rs.getString("email");
            }
        }
    }
} catch (Exception e) {
    getServletContext().log("이메일 조회 오류", e);
}

// 소개글 파일 불러오기 (.jsp 실행 없이 안전하게 출력)
try {
    String path = application.getRealPath("/templates/user_" + username + ".txt");
    File f = new File(path);
    if (f.exists()) {
        StringBuilder sb = new StringBuilder();
        try (BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(f), "UTF-8"))) {
            String line;
            while ((line = br.readLine()) != null) {
                sb.append(line).append("\n");
            }
        }
        introOutput = StringEscapeUtils.escapeHtml4(sb.toString());
    } else {
        introOutput = "<em>소개글이 없습니다.</em>";
    }
} catch (Exception e) {
    getServletContext().log("소개글 파일 로딩 실패", e);
    introOutput = "<em>소개글 불러오기 중 오류 발생</em>";
}

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>마이페이지</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"mypage_styles.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <main class=\"mypage-main\" style=\"max-width:480px; margin:0 auto; padding:18px 8px 120px 8px; box-sizing:border-box;\">\n");
      out.write("        <div class=\"post-card\" style=\"background:#333; border-radius:12px; margin-bottom:18px; padding:20px 14px 14px 14px; box-shadow:0 2px 8px rgba(0,0,0,0.12);\">\n");
      out.write("            <div style=\"display:flex; align-items:center; gap:14px; margin-bottom:10px;\">\n");
      out.write("                <div class=\"profile-pic\" style=\"width:54px; height:54px; border-radius:50%; background:#222 url('/image/profile.png') center/cover no-repeat; border:2px solid #ffe082;\"></div>\n");
      out.write("                <div>\n");
      out.write("                    <div style=\"font-size:1.15em; color:#ffe082; font-weight:bold; margin-bottom:2px; word-break:break-all;\">👤 ");
      out.print( StringEscapeUtils.escapeHtml4(username) );
      out.write("</div>\n");
      out.write("                    <div style=\"font-size:0.98em; color:#bbb; word-break:break-all;\">✉️ ");
      out.print( StringEscapeUtils.escapeHtml4(email) );
      out.write("</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"intro-box\" style=\"background:#232323; border-radius:8px; padding:12px 10px; color:#fff; margin-bottom:12px;\">\n");
      out.write("                <div style=\"color:#ffe082; font-size:1em; margin-bottom:4px;\"><strong>소개글</strong></div>\n");
      out.write("                <pre style=\"background:none; color:#fff; font-size:1.05em; margin:0; border:none; padding:0; white-space:pre-wrap; word-break:break-all;\">");
      out.print( introOutput );
      out.write("</pre>\n");
      out.write("            </div>\n");
      out.write("            <div style=\"display:flex; gap:10px; margin-top:10px;\">\n");
      out.write("                <a href=\"/mobile/mypage/edit.jsp\" class=\"edit-btn\" style=\"flex:1; background:#ffe082; color:#222; border-radius:8px; padding:10px 0; text-align:center; font-weight:bold; text-decoration:none;\">소개글 수정</a>\n");
      out.write("                <a href=\"/mobile/login/logout.jsp\" class=\"logout-btn\" style=\"flex:1; background:#e53935; color:#fff; border-radius:8px; padding:10px 0; text-align:center; font-weight:bold; text-decoration:none;\">로그아웃</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <footer class=\"mobile-footer\">\n");
      out.write("            <span style=\"font-size:1.1em;\">&copy; 2025 TESTGAMES</span><br>\n");
      out.write("            <span style=\"font-size:0.98em; color:#bbb;\">이 웹사이트는 테스트 용도로 만들어졌습니다.</span>\n");
      out.write("        </footer>\n");
      out.write("    </main>\n");
      out.write("    <nav class=\"mobile-nav\">\n");
      out.write("        <a href=\"/mobile/index.jsp\">\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\"><path d=\"M3 12L12 4l9 8\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M5 10v10h14V10\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>\n");
      out.write("            홈\n");
      out.write("        </a>\n");
      out.write("        <a href=\"/mobile/board/board.jsp\">\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\"><rect x=\"3\" y=\"5\" width=\"18\" height=\"14\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M7 10h10M7 14h6\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>\n");
      out.write("            게시판\n");
      out.write("        </a>\n");
      out.write("        <a href=\"/mobile/mypage/mypage.jsp\" class=\"active\">\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\"><circle cx=\"12\" cy=\"8\" r=\"4\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M4 20c0-4 4-7 8-7s8 3 8 7\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>\n");
      out.write("            마이페이지\n");
      out.write("        </a>\n");
      out.write("    </nav>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
