/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-07-16 01:50:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mobile.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import java.util.*;
import io.jsonwebtoken.*;
import javax.crypto.spec.SecretKeySpec;
import java.security.Key;
import org.apache.commons.text.StringEscapeUtils;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("io.jsonwebtoken");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.security.Key");
    _jspx_imports_classes.add("javax.crypto.spec.SecretKeySpec");
    _jspx_imports_classes.add("org.apache.commons.text.StringEscapeUtils");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    request.setCharacterEncoding("UTF-8");

    boolean isLoggedIn = false;
    String username = "";
    String token = null;

    Cookie[] cookies = request.getCookies();
    if (cookies != null) {
        for (Cookie cookie : cookies) {
            if ("authToken".equals(cookie.getName())) {
                token = cookie.getValue();
                break;
            }
        }
    }

    if (token != null) {
        try {
            String jwtSecret = System.getenv("JWT_SECRET");
            if (jwtSecret != null) {
                byte[] keyBytes = jwtSecret.getBytes("UTF-8");
                Key signingKey = new SecretKeySpec(keyBytes, SignatureAlgorithm.HS256.getJcaName());

                Claims claims = Jwts.parserBuilder()
                    .setSigningKey(signingKey)
                    .build()
                    .parseClaimsJws(token)
                    .getBody();

                isLoggedIn = true;
                username = claims.getSubject();
            } else {
                getServletContext().log("JWT_SECRET not set.");
            }
        } catch (Exception e) {
            getServletContext().log("JWT parse error", e);
        }
    }

    String dbURL = System.getenv("DB_URL");
    String dbUser = System.getenv("DB_USER");
    String dbPassword = System.getenv("DB_PASSWORD");

    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;

    String query = request.getParameter("query");
    if (query == null) query = "";
    String trimmedQuery = query.trim();
    boolean isSearch = !trimmedQuery.isEmpty();

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>게시판</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"board_styles.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<main class=\"board-main\">\n");
      out.write("    <h1>BLOG</h1>\n");
      out.write("    <div style=\"text-align:center; color:#ffe082; font-size:1.08em; margin-bottom:10px;\">\n");
      out.write("        게임 소식과 업데이트를 확인하세요!\n");
      out.write("    </div>\n");
      out.write("    <form class=\"search-bar\" action=\"board.jsp\" method=\"get\">\n");
      out.write("        <input type=\"text\" name=\"query\" placeholder=\"검색어를 입력하세요\" value=\"");
      out.print( StringEscapeUtils.escapeHtml4(query) );
      out.write("\" required>\n");
      out.write("        <button type=\"submit\">🔍</button>\n");
      out.write("    </form>\n");
      out.write("    <a href=\"/mobile/write/write.jsp\" class=\"write-btn\">✏️ 글쓰기</a>\n");
      out.write("\n");
      out.write("    ");
 if (isSearch) { 
      out.write("\n");
      out.write("        <div style=\"text-align:center; color:#ffe082; font-size:1.05em; margin-bottom:8px;\">\n");
      out.write("            \"");
      out.print( StringEscapeUtils.escapeHtml4(query) );
      out.write("\" 검색 결과\n");
      out.write("        </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"post-list\">\n");
      out.write("    ");

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(dbURL, dbUser, dbPassword);

            String sql = isSearch
                ? "SELECT id, username, title, created_at FROM posts WHERE title LIKE ? OR content LIKE ? ORDER BY created_at DESC LIMIT 10"
                : "SELECT id, username, title, created_at FROM posts ORDER BY created_at DESC LIMIT 10";

            pstmt = conn.prepareStatement(sql);

            if (isSearch) {
                String keyword = "%" + trimmedQuery + "%";
                pstmt.setString(1, keyword);
                pstmt.setString(2, keyword);
            }

            rs = pstmt.executeQuery();
            int count = 0;
            while (rs.next()) {
                int postId = rs.getInt("id");
                String writer = StringEscapeUtils.escapeHtml4(rs.getString("username"));
                String title = StringEscapeUtils.escapeHtml4(rs.getString("title"));
                String created = StringEscapeUtils.escapeHtml4(rs.getString("created_at"));
    
      out.write("\n");
      out.write("        <div class=\"post-card\">\n");
      out.write("            <a href=\"/mobile/view/view.jsp?id=");
      out.print( postId );
      out.write("\" class=\"post-title\">");
      out.print( title );
      out.write("</a>\n");
      out.write("            <div class=\"post-meta\">\n");
      out.write("                <span>👤 ");
      out.print( writer );
      out.write("</span>\n");
      out.write("                <span>🕒 ");
      out.print( created );
      out.write("</span>\n");
      out.write("                <span style=\"margin-left:auto; color:#ffe082; font-size:0.98em;\">#");
      out.print( postId );
      out.write("</span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    ");

                count++;
            }
            if (count == 0) {
    
      out.write("\n");
      out.write("        <div style=\"text-align:center; color:#bbb; margin:18px 0;\">검색 결과가 없습니다.</div>\n");
      out.write("    ");

            }
        } catch (Exception e) {
            getServletContext().log("게시글 목록 오류", e);
            out.println("<div style='color:#e53935; text-align:center; margin:18px 0;'>데이터를 불러오는 중 오류가 발생했습니다.</div>");
        } finally {
            try { if (rs != null) rs.close(); } catch (Exception e) {}
            try { if (pstmt != null) pstmt.close(); } catch (Exception e) {}
            try { if (conn != null) conn.close(); } catch (Exception e) {}
        }
    
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("<footer class=\"mobile-footer\">\n");
      out.write("    <span style=\"font-size:1.1em;\">&copy; 2025 TESTGAMES</span><br>\n");
      out.write("    <span style=\"font-size:0.98em; color:#bbb;\">이 웹사이트는 테스트 용도로 만들어졌습니다.</span>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- 모바일 하단 네비게이션 -->\n");
      out.write("<nav class=\"mobile-nav\">\n");
      out.write("    <a href=\"/mobile/index.jsp\">\n");
      out.write("        <svg viewBox=\"0 0 24 24\" fill=\"none\"><path d=\"M3 12L12 4l9 8\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M5 10v10h14V10\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>\n");
      out.write("        홈\n");
      out.write("    </a>\n");
      out.write("    <a href=\"/mobile/board/board.jsp\">\n");
      out.write("        <svg viewBox=\"0 0 24 24\" fill=\"none\"><rect x=\"3\" y=\"5\" width=\"18\" height=\"14\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M7 10h10M7 14h6\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>\n");
      out.write("        게시판\n");
      out.write("    </a>\n");
      out.write("    <a href=\"/mobile/mypage/mypage.jsp\">\n");
      out.write("        <svg viewBox=\"0 0 24 24\" fill=\"none\"><circle cx=\"12\" cy=\"8\" r=\"4\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M4 20c0-4 4-7 8-7s8 3 8 7\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>\n");
      out.write("        마이페이지\n");
      out.write("    </a>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
