/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-07-17 04:58:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mobile.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">\n");
      out.write("    <title>로그인</title>\n");
      out.write("    <!-- 모바일 전용 로그인 CSS -->\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"login_styles.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"login-main\">\n");
      out.write("        <h1>LOGIN</h1>\n");
      out.write("\n");
      out.write("        <form action=\"processLogin.jsp\" method=\"post\">\n");
      out.write("            <label for=\"username\">ID</label>\n");
      out.write("            <input \n");
      out.write("                type=\"text\" \n");
      out.write("                id=\"username\" \n");
      out.write("                name=\"username\" \n");
      out.write("                placeholder=\"아이디 입력\" \n");
      out.write("                required\n");
      out.write("            >\n");
      out.write("\n");
      out.write("            <label for=\"password\">Password</label>\n");
      out.write("            <input \n");
      out.write("                type=\"password\" \n");
      out.write("                id=\"password\" \n");
      out.write("                name=\"password\" \n");
      out.write("                placeholder=\"비밀번호 입력\" \n");
      out.write("                required\n");
      out.write("            >\n");
      out.write("\n");
      out.write("            <button type=\"submit\">Login</button>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <div class=\"login-links\" style=\"display:flex; gap:10px; justify-content:center; margin-top:20px;\">\n");
      out.write("            <a href=\"/mobile/login/edit_pass.jsp\" style=\"\n");
      out.write("                display:inline-flex; align-items:center; gap:6px;\n");
      out.write("                background:#ffe082; color:#232323; font-weight:600;\n");
      out.write("                border-radius: 18px; padding: 10px 18px; font-size:1em;\n");
      out.write("                box-shadow:0 2px 8px #0002; text-decoration:none;\n");
      out.write("                transition:background 0.18s, color 0.18s, transform 0.13s;\n");
      out.write("            \" onmouseover=\"this.style.background='#e53935';this.style.color='#fff';this.style.transform='scale(1.04)';\" onmouseout=\"this.style.background='#ffe082';this.style.color='#232323';this.style.transform='none';\">\n");
      out.write("                <span style=\"font-size:1.2em;\">🔑</span> 비밀번호 변경\n");
      out.write("            </a>\n");
      out.write("            <a href=\"/mobile/signup/signup.jsp\" style=\"\n");
      out.write("                display:inline-flex; align-items:center; gap:6px;\n");
      out.write("                background:#8e24aa; color:#fff; font-weight:600;\n");
      out.write("                border-radius: 18px; padding: 10px 18px; font-size:1em;\n");
      out.write("                box-shadow:0 2px 8px #0002; text-decoration:none;\n");
      out.write("                transition:background 0.18s, color 0.18s, transform 0.13s;\n");
      out.write("            \" onmouseover=\"this.style.background='#5e35b1';this.style.color='#fffde7';this.style.transform='scale(1.04)';\" onmouseout=\"this.style.background='#8e24aa';this.style.color='#fff';this.style.transform='none';\">\n");
      out.write("                <span style=\"font-size:1.2em; color:#fff;\">👤</span> 회원가입\n");
      out.write("            </a>\n");
      out.write("            <a href=\"/mobile/index.jsp\" style=\"\n");
      out.write("                display:inline-flex; align-items:center; gap:6px;\n");
      out.write("                background:#43c43a; color:#fff; font-weight:600;\n");
      out.write("                border-radius: 18px; padding: 10px 18px; font-size:1em;\n");
      out.write("                box-shadow:0 2px 8px #0002; text-decoration:none;\n");
      out.write("                transition:background 0.18s, color 0.18s, transform 0.13s;\n");
      out.write("            \" onmouseover=\"this.style.background='#388e3c';this.style.color='#fffde7';this.style.transform='scale(1.04)';\" onmouseout=\"this.style.background='#43c43a';this.style.color='#fff';this.style.transform='none';\">\n");
      out.write("                <span style=\"font-size:1.2em;\">🏠</span> 메인으로\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
