/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-07-17 06:22:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mobile.write;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.UUID;

public final class write_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.UUID");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

String csrfToken = UUID.randomUUID().toString();
session.setAttribute("csrfToken", csrfToken);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>글쓰기</title>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"write_styles.css\">\n");
      out.write("    <script>\n");
      out.write("        function buildXMLandSubmit() {\n");
      out.write("            const title = document.querySelector('input[name=\"title\"]').value;\n");
      out.write("            const content = document.querySelector('textarea[name=\"content\"]').value;\n");
      out.write("\n");
      out.write("            const xml =\n");
      out.write("                \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n\" +\n");
      out.write("                \"<post>\\n\" +\n");
      out.write("                \"  <title>\" + escapeXml(title) + \"</title>\\n\" +\n");
      out.write("                \"  <content>\" + escapeXml(content) + \"</content>\\n\" +\n");
      out.write("                \"</post>\";\n");
      out.write("\n");
      out.write("            document.getElementById(\"xmlField\").value = xml;\n");
      out.write("            return true;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function escapeXml(str) {\n");
      out.write("            return str.replace(/&/g, \"&amp;\")\n");
      out.write("                      .replace(/</g, \"&lt;\")\n");
      out.write("                      .replace(/>/g, \"&gt;\")\n");
      out.write("                      .replace(/\\\"/g, \"&quot;\")\n");
      out.write("                      .replace(/\\'/g, \"&apos;\");\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<main class=\"write-main\">\n");
      out.write("    <div class=\"write-card\">\n");
      out.write("        <div class=\"write-title\">✏️ 글쓰기</div>\n");
      out.write("        <form action=\"writeProcess.jsp\" method=\"post\" enctype=\"multipart/form-data\" onsubmit=\"return buildXMLandSubmit();\">\n");
      out.write("            <input type=\"hidden\" name=\"csrfToken\" id=\"csrfToken\" value=\"");
      out.print( csrfToken );
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"xml\" id=\"xmlField\">\n");
      out.write("\n");
      out.write("            <label for=\"title\" class=\"write-label\">제목</label>\n");
      out.write("            <input type=\"text\" name=\"title\" id=\"title\" class=\"write-input\" required>\n");
      out.write("\n");
      out.write("            <label for=\"content\" class=\"write-label\">내용</label>\n");
      out.write("            <textarea name=\"content\" id=\"content\" class=\"write-textarea\" rows=\"6\" required></textarea>\n");
      out.write("\n");
      out.write("            <label for=\"file\" class=\"write-label\">파일 업로드</label>\n");
      out.write("            <input type=\"file\" name=\"file\" id=\"file\" class=\"write-file\">\n");
      out.write("\n");
      out.write("            <button type=\"submit\" class=\"write-btn\">전송</button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("<footer class=\"mobile-footer\">\n");
      out.write("    <span style=\"font-size:1.1em;\">&copy; 2025 TESTGAMES</span><br>\n");
      out.write("    <span style=\"font-size:0.98em; color:#bbb;\">이 웹사이트는 테스트 용도로 만들어졌습니다.</span>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- 모바일 하단 네비게이션 -->\n");
      out.write("<nav class=\"mobile-nav\">\n");
      out.write("    <a href=\"/mobile/index.jsp\">\n");
      out.write("        <svg viewBox=\"0 0 24 24\" fill=\"none\"><path d=\"M3 12L12 4l9 8\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M5 10v10h14V10\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>\n");
      out.write("        홈\n");
      out.write("    </a>\n");
      out.write("    <a href=\"/mobile/board/board.jsp\">\n");
      out.write("        <svg viewBox=\"0 0 24 24\" fill=\"none\"><rect x=\"3\" y=\"5\" width=\"18\" height=\"14\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M7 10h10M7 14h6\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>\n");
      out.write("        게시판\n");
      out.write("    </a>\n");
      out.write("    <a href=\"/mobile/mypage/mypage.jsp\">\n");
      out.write("        <svg viewBox=\"0 0 24 24\" fill=\"none\"><circle cx=\"12\" cy=\"8\" r=\"4\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M4 20c0-4 4-7 8-7s8 3 8 7\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>\n");
      out.write("        마이페이지\n");
      out.write("    </a>\n");
      out.write("</nav>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
